apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-deployment
  labels:
    app: django-k8s-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      project: django-web-app
  template:
    metadata:
      labels:
        project: django-web-app
    spec:
      containers:
      - name: django
        image: weffy/django_app:latest
        envFrom:
          - secretRef:
              name: django-secret
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: django-service
  labels:
    app: django
spec:
  type: ClusterIP
  selector:
    project: django-web-app
  ports:
    - port: 80
      targetPort: 80

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: django-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    - host: star-burger.test
      http:
        paths:
        - pathType: Prefix
          path: /
          backend:
            service:
              name: django-service
              port:
                number: 80
