apiVersion: v1
kind: Pod
metadata:
  name: test-ubuntu-pod
spec:
  volumes:
    - name: postgres-key
      secret:
        secretName: postgres-ssl-key
        defaultMode: 384
  containers:
  - name: test-ubuntu-container
    image: ubuntu:latest
    command: [ "/bin/sh", "-c" ]
    args:
      - apt-get update && apt-get install -y postgresql-client;
        sleep infinity;
    volumeMounts:
      - name: postgres-key
        readOnly: true
        mountPath: "/root/.postgresql/"